### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by albi2** [juancruzmartino/wg-gesucht-scrapper#4]

**Comment by Asada1** [comment]
I try to make it run, now I have a problem with accepting cookies.

**Comment by Asada1** [comment]
I get this error. Honestly I have no clue what I'm doing so any help will be appriciated.

Error: Request failed with status code 404
    at createError (/Users/ac/Downloads/wg-gesucht-scrapper-master/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/ac/Downloads/wg-gesucht-scrapper-master/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/ac/Downloads/wg-gesucht-scrapper-master/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (node:events:519:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  config: {


[...] //basicly the whole code of the program so I skip it


TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "cookie"
    at ClientRequest.setHeader (node:_http_outgoing:702:3)
    at new ClientRequest (node:_http_client:302:14)
    at Object.request (node:https:381:10)
    at RedirectableRequest._performRequest (/Users/ac/Downloads/wg-gesucht-scrapper-master/node_modules/follow-redirects/index.js:169:24)
    at new RedirectableRequest (/Users/ac/Downloads/wg-gesucht-scrapper-master/node_modules/follow-redirects/index.js:66:8)
    at wrappedProtocol.request (/Users/ac/Downloads/wg-gesucht-scrapper-master/node_modules/follow-redirects/index.js:307:14)
    at dispatchHttpRequest (/Users/ac/Downloads/wg-gesucht-scrapper-master/node_modules/axios/lib/adapters/http.js:180:25)
    at new Promise (<anonymous>)
    at httpAdapter (/Users/ac/Downloads/wg-gesucht-scrapper-master/node_modules/axios/lib/adapters/http.js:20:10)
    at dispatchRequest (/Users/ac/Downloads/wg-gesucht-scrapper-master/node_modules/axios/lib/core/dispatchRequest.js:59:10) {
  code: 'ERR_HTTP_INVALID_HEADER_VALUE'
}
TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "cookie"
    at ClientRequest.setHeader (node:_http_outgoing:702:3)
    at new ClientRequest (node:_http_client:302:14)
    at Object.request (node:https:381:10)
    at RedirectableRequest._performRequest (/Users/ac/Downloads/wg-gesucht-scrapper-master/node_modules/follow-redirects/index.js:169:24)
    at new RedirectableRequest (/Users/ac/Downloads/wg-gesucht-scrapper-master/node_modules/follow-redirects/index.js:66:8)
    at wrappedProtocol.request (/Users/ac/Downloads/wg-gesucht-scrapper-master/node_modules/follow-redirects/index.js:307:14)
    at dispatchHttpRequest (/Users/ac/Downloads/wg-gesucht-scrapper-master/node_modules/axios/lib/adapters/http.js:180:25)
    at new Promise (<anonymous>)
    at httpAdapter (/Users/ac/Downloads/wg-gesucht-scrapper-master/node_modules/axios/lib/adapters/http.js:20:10)
    at dispatchRequest (/Users/ac/Downloads/wg-gesucht-scrapper-master/node_modules/axios/lib/core/dispatchRequest.js:59:10) {
  code: 'ERR_HTTP_INVALID_HEADER_VALUE'
}
